version: 2
updates:
  - package-ecosystem: docker
    directory: go-builder
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: go-runtime
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
